//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineSweeper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineSweeper.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This square contains {0} adjacent mines..
        /// </summary>
        internal static string AdjacentMineWarning {
            get {
                return ResourceManager.GetString("AdjacentMineWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no, you detonated a mine! Game over..
        /// </summary>
        internal static string GameOverText {
            get {
                return ResourceManager.GetString("GameOverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you have won the game!.
        /// </summary>
        internal static string GameWonText {
            get {
                return ResourceManager.GetString("GameWonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the size of the grid (e.g. 4 for a 4x4 grid):.
        /// </summary>
        internal static string GridInputHelpText {
            get {
                return ResourceManager.GetString("GridInputHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size of grid is {0}.
        /// </summary>
        internal static string GridMaxValidation {
            get {
                return ResourceManager.GetString("GridMaxValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum size of grid is {0}..
        /// </summary>
        internal static string GridMinValidation {
            get {
                return ResourceManager.GetString("GridMinValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorect input..
        /// </summary>
        internal static string IncorrectInput {
            get {
                return ResourceManager.GetString("IncorrectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is your minefield:.
        /// </summary>
        internal static string MineFieldShowText {
            get {
                return ResourceManager.GetString("MineFieldShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of mines to place on the grid (maximum is 35% of the total squares):.
        /// </summary>
        internal static string MinesInputHelpText {
            get {
                return ResourceManager.GetString("MinesInputHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number is 35% of total sqaures..
        /// </summary>
        internal static string MinesMaxValidation {
            get {
                return ResourceManager.GetString("MinesMaxValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least 1 mine..
        /// </summary>
        internal static string MinesMinValidation {
            get {
                return ResourceManager.GetString("MinesMinValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to play again....
        /// </summary>
        internal static string PlayAgainText {
            get {
                return ResourceManager.GetString("PlayAgainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a square to reveal (e.g. A1):.
        /// </summary>
        internal static string SelectCellText {
            get {
                return ResourceManager.GetString("SelectCellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is your updated minefield:.
        /// </summary>
        internal static string UpdateMineFieldShowText {
            get {
                return ResourceManager.GetString("UpdateMineFieldShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Minesweeper!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
